train:
  model_cfg: misc/model.yaml
  # train args
  lr: 2.5e-5
  epoches: 5

  logging_steps: 50

  # dataloader
  train_batch_size: 32
  train_num_workers: 4

  eval_batch_size: 16
  eval_num_workers: 4
  # optim
  weight_decay: 0.05
  warmup_ratio: 0.2

  # work_dir
  work_dir: work_dir/test/